/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/@types/img.d`; params?: Router.UnknownInputParams; } | { pathname: `/addUserPage`; params?: Router.UnknownInputParams; } | { pathname: `/addUserPage/styles`; params?: Router.UnknownInputParams; } | { pathname: `/homePage`; params?: Router.UnknownInputParams; } | { pathname: `/homePage/styles`; params?: Router.UnknownInputParams; } | { pathname: `/orcamentoPage`; params?: Router.UnknownInputParams; } | { pathname: `/orcamentoPage/styles`; params?: Router.UnknownInputParams; } | { pathname: `/vizualizePage`; params?: Router.UnknownInputParams; } | { pathname: `/vizualizePage/styles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/@types/img.d`; params?: Router.UnknownOutputParams; } | { pathname: `/addUserPage`; params?: Router.UnknownOutputParams; } | { pathname: `/addUserPage/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/homePage`; params?: Router.UnknownOutputParams; } | { pathname: `/homePage/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/orcamentoPage`; params?: Router.UnknownOutputParams; } | { pathname: `/orcamentoPage/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/vizualizePage`; params?: Router.UnknownOutputParams; } | { pathname: `/vizualizePage/styles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/@types/img.d${`?${string}` | `#${string}` | ''}` | `/addUserPage${`?${string}` | `#${string}` | ''}` | `/addUserPage/styles${`?${string}` | `#${string}` | ''}` | `/homePage${`?${string}` | `#${string}` | ''}` | `/homePage/styles${`?${string}` | `#${string}` | ''}` | `/orcamentoPage${`?${string}` | `#${string}` | ''}` | `/orcamentoPage/styles${`?${string}` | `#${string}` | ''}` | `/vizualizePage${`?${string}` | `#${string}` | ''}` | `/vizualizePage/styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/@types/img.d`; params?: Router.UnknownInputParams; } | { pathname: `/addUserPage`; params?: Router.UnknownInputParams; } | { pathname: `/addUserPage/styles`; params?: Router.UnknownInputParams; } | { pathname: `/homePage`; params?: Router.UnknownInputParams; } | { pathname: `/homePage/styles`; params?: Router.UnknownInputParams; } | { pathname: `/orcamentoPage`; params?: Router.UnknownInputParams; } | { pathname: `/orcamentoPage/styles`; params?: Router.UnknownInputParams; } | { pathname: `/vizualizePage`; params?: Router.UnknownInputParams; } | { pathname: `/vizualizePage/styles`; params?: Router.UnknownInputParams; };
    }
  }
}
